WIP: Switch to profiles
openshift/cluster-kube-scheduler-operator pull request #307
Opened 2020-12-03 13:05 UTC by ingvagabund

Based on https://github.com/openshift/enhancements/blob/master/enhancements/scheduling/scheduler-profiles.md

2020-12-03 15:34 UTC, ingvagabund commented
`schedulers.config.openshift.io` CRD needs to be updated first: https://github.com/openshift/api/pull/806

2020-12-04 16:37 UTC, soltysh approved these changes
/lgtm
/hold

2020-12-04 17:42 UTC, damemi requested changes
the new code to use the profiles looks good, pretty straightforward. but we should probably have some sort of logging for when `policy` is still set to indicate that it's deprecated, and also disallow setting both `policy` and `profile`

2020-12-04 17:42 UTC, damemi commented on pkg/operator/targetconfigcontroller/targetconfigcontroller.go
> +
nit: new extra line

2020-12-04 17:42 UTC, damemi commented on pkg/operator/targetconfigcontroller/targetconfigcontroller.go
> +	requiredConfigMap, _, err := resourcemerge.MergeConfigMap(configMap, "config.yaml", nil, kubeSchedulerConfiguration, operatorSpec.ObservedConfig.Raw, operatorSpec.UnsupportedConfigOverrides.Raw)
how does this handle if the user sets a custom policy *and* a profile?

2020-12-04 18:16 UTC, ingvagabund commented
/retest

2020-12-04 18:23 UTC, damemi approved these changes
/lgtm
/hold cancel

Thanks @ingvagabund !

2020-12-04 20:07 UTC, ingvagabund commented
/retest

2020-12-04 20:12 UTC, ingvagabund commented
/retest

2020-12-04 22:35 UTC, merged